In [152]:
import pandas as pd

In [153]:
train = pd.read_csv('기술통계19.csv',index_col='global_id')

In [154]:
service = pd.read_csv('실태조사_서비스업19.csv',index_col='global_id')
normal = pd.read_csv('실태조사_일반항목19.csv',index_col='global_id')
product = pd.read_csv('실태조사_제조업19.csv',index_col='global_id')

C:\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3057: DtypeWarning: Columns (54,84,102) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [155]:
train

,x1,x3,x2,SEX,AGE,YEAR,MAININCM,05-Sep,04-Sep,01-Sep,...,I4Q5,I4S6,I4Q6,I4S7,I4Q7,I5,I6_1,I6_2,I7_1,I7_2
global_id,,,,,,,,,,,,,,,,,,,,,
111001,11,33,1,2,1976.0,2010,100.0,2,1,0,...,3,0,3,0,3,1,9.0,NaN,3.0,NaN
111002,11,63,6,1,1970.0,2000,100.0,3,0,1,...,2,0,2,0,2,1,2.0,4.0,1.0,3.0
111003,31,23,7,1,1965.0,2000,100.0,3,1,0,...,3,0,3,0,3,1,2.0,NaN,2.0,NaN
111004,32,27,2,1,1965.0,2002,56.0,3,0,1,...,3,0,3,0,3,2,3.0,6.0,1.0,4.0
111005,31,26,2,1,1952.0,2002,80.0,3,1,0,...,3,0,3,0,3,1,9.0,8.0,1.0,4.0
111006,11,27,2,1,1957.0,2003,100.0,3,0,0,...,2,0,3,0,2,1,1.0,7.0,6.0,1.0
111007,33,21,3,1,1960.0,2004,100.0,2,0,1,...,3,0,3,0,3,4,1.0,NaN,1.0,NaN
111008,11,62,2,1,1961.0,2005,80.0,2,0,0,...,2,0,4,0,2,2,3.0,NaN,1.0,2.0
111009,11,70,1,1,1977.0,2009,100.0,3,1,0,...,2,0,2,0,2,1,1.0,6.0,2.0,NaN
111010,11,33,1,1,1965.0,2003,90.0,2,0,1,...,3,0,3,0,3,1,9.0,NaN,1.0,NaN
111011,21,70,1,1,1972.0,2012,100.0,1,0,0,...,1,0,1,0,1,1,6.0,7.0,1.0,4.0
111012,11,33,3,1,1974.0,2013,100.0,2,1,0,...,3,0,3,0,3,1,9.0,NaN,1.0,NaN
111013,33,29,2,1,1973.0,2016,60.0,1,1,0,...,1,0,1,0,1,1,3.0,4.0,1.0,3.0
111014,11,63,6,1,1958.0,1995,100.0,3,1,0,...,2,0,2,0,2,1,3.0,4.0,4.0,NaN
111015,31,62,1,1,1973.0,2017,100.0,1,1,0,...,3,0,3,0,3,2,3.0,6.0,2.0,3.0
111016,11,73,1,1,1965.0,1989,100.0,3,1,0,...,1,0,3,0,3,3,6.0,8.0,1.0,3.0
111017,11,70,1,1,1972.0,2012,100.0,2,1,0,...,3,0,3,0,3,1,1.0,3.0,1.0,3.0
111018,31,13,1,1,1940.0,2015,100.0,2,1,0,...,3,0,1,0,3,2,4.0,NaN,1.0,6.0
111019,31,25,1,1,1957.0,2002,100.0,3,1,0,...,2,0,2,0,2,2,9.0,NaN,1.0,NaN
111020,31,18,2,1,1954.0,1985,100.0,3,1,0,...,1,0,2,0,2,1,9.0,6.0,3.0,1.0
111021,31,18,3,1,1948.0,1974,100.0,2,1,0,...,1,0,2,0,2,1,6.0,9.0,3.0,4.0
111022,25,27,6,2,1957.0,1989,90.0,3,0,0,...,1,0,1,0,1,1,1.0,6.0,1.0,3.0
111023,31,15,6,1,1964.0,1994,100.0,3,1,0,...,3,0,3,0,3,1,4.0,8.0,2.0,1.0
111024,33,32,7,1,1955.0,1996,100.0,3,0,0,...,3,0,2,0,2,1,3.0,4.0,1.0,5.0
111025,23,30,6,1,1965.0,1996,70.0,3,1,0,...,3,0,3,0,3,3,3.0,2.0,1.0,4.0
111026,31,72,2,1,1958.0,2001,70.0,3,1,0,...,3,0,3,0,3,4,9.0,6.0,1.0,7.0
111027,38,10,3,1,1965.0,2000,100.0,3,0,1,...,1,0,1,0,1,1,3.0,4.0,1.0,4.0
111028,31,73,1,1,1959.0,2002,100.0,2,1,0,...,3,0,3,0,3,3,6.0,3.0,1.0,2.0
111029,11,73,1,1,1965.0,2003,100.0,2,0,0,...,1,0,3,0,3,1,8.0,6.0,1.0,3.0
111030,25,70,1,1,1964.0,2004,80.0,2,0,0,...,1,0,3,0,3,1,2.0,NaN,1.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
114771,37,30,1,1,1979.0,2016,80.0,1,1,0,...,2,0,1,0,2,2,3.0,8.0,1.0,2.0
114772,11,73,2,1,1985.0,2015,100.0,1,1,0,...,1,0,3,0,3,1,9.0,8.0,1.0,3.0
114773,31,30,3,1,1966.0,1987,100.0,3,1,0,...,2,0,2,0,2,2,2.0,7.0,1.0,NaN
114774,21,311,2,1,1972.0,2016,100.0,1,0,1,...,3,0,3,0,3,1,1.0,NaN,1.0,NaN
114775,34,22,1,1,1975.0,2015,40.0,2,1,0,...,3,0,2,0,1,1,3.0,2.0,1.0,4.0
114776,21,15,2,2,1962.0,2015,100.0,1,1,0,...,3,0,3,0,3,2,3.0,6.0,2.0,4.0
114777,37,311,1,1,1978.0,2016,50.0,1,0,0,...,3,0,3,0,3,2,3.0,4.0,7.0,3.0
114778,26,28,1,1,1974.0,2014,100.0,2,0,0,...,3,0,4,0,2,1,3.0,NaN,6.0,5.0
114779,39,33,1,2,1973.0,2016,100.0,1,0,0,...,3,0,3,0,3,2,1.0,7.0,2.0,3.0
114780,33,21,4,1,1960.0,2015,60.0,1,1,0,...,1,0,1,0,1,1,1.0,3.0,1.0,4.0
114781,22,14,1,1,1984.0,2016,90.0,1,1,0,...,1,0,1,0,1,1,7.0,NaN,1.0,3.0
114782,23,26,2,1,1970.0,2017,50.0,1,1,0,...,1,0,2,0,2,4,1.0,2.0,3.0,4.0
114783,33,26,2,1,1957.0,2015,70.0,2,1,0,...,1,0,1,0,1,1,1.0,3.0,1.0,4.0
114784,33,20,1,1,1966.0,2017,100.0,1,0,0,...,1,0,2,0,2,3,3.0,1.0,1.0,6.0
114785,31,24,2,1,1965.0,2016,100.0,2,0,0,...,2,0,2,0,2,1,1.0,8.0,1.0,2.0
114786,21,10,1,1,1976.0,2017,100.0,1,0,0,...,3,0,3,0,3,1,3.0,NaN,4.0,NaN
114787,35,16,2,1,1962.0,2016,80.0,2,1,0,...,3,0,3,0,3,2,3.0,1.0,1.0,3.0
114788,36,311,2,1,1965.0,2015,80.0,2,1,0,...,2,0,3,0,3,3,1.0,4.0,2.0,3.0
114789,33,70,1,1,1977.0,2015,100.0,2,0,1,...,2,0,2,0,3,1,1.0,3.0,1.0,5.0
114790,22,30,5,1,1957.0,2016,60.0,1,0,1,...,2,0,2,0,2,1,3.0,6.0,1.0,7.0
114791,22,14,1,2,1965.0,2016,100.0,3,0,0,...,1,0,2,0,2,1,4.0,5.0,3.0,4.0
114792,33,20,7,1,1960.0,2016,80.0,2,0,1,...,2,0,2,0,1,2,3.0,1.0,1.0,5.0
114793,38,30,6,2,1984.0,2012,95.0,1,1,0,...,3,0,3,0,3,4,3.0,6.0,2.0,6.0
114794,21,29,3,1,1984.0,2015,100.0,3,1,0,...,1,0,1,0,1,1,8.0,9.0,1.0,4.0
114795,33,33,3,1,1962.0,2017,30.0,2,1,0,...,3,0,4,0,4,1,3.0,NaN,1.0,7.0
114796,31,73,2,2,1983.0,2012,80.0,2,1,0,...,3,0,3,0,3,1,8.0,NaN,3.0,NaN
114797,38,311,2,1,1982.0,2015,100.0,4,1,0,...,3,0,3,0,3,2,4.0,8.0,1.0,2.0
114798,33,16,1,1,1976.0,2016,90.0,2,0,0,...,3,0,3,0,3,2,9.0,4.0,1.0,5.0
114799,25,70,1,1,1975.0,2016,80.0,2,0,0,...,3,0,3,0,3,1,1.0,3.0,NaN,NaN
114800,25,73,1,1,1973.0,2016,100.0,2,1,0,...,1,0,1,0,1,1,1.0,NaN,1.0,3.0

In [156]:
# line=[]
# for i in service.index:
#     line.append(i)
#     if not i in train.index:
#         line.remove(i)

In [157]:
line=[]
for i in train.index:
    line.append(i)
    if not i in service.index:
        line.remove(i)

In [158]:
line

[111016,
 111037,
 111039,
 111041,
 111055,
 111061,
 111097,
 111098,
 111117,
 111140,
 111148,
 111163,
 111176,
 111180,
 111181,
 111186,
 111208,
 111246,
 111263,
 111278,
 111281,
 111313,
 111403,
 111436,
 111483,
 111573,
 111583,
 111586,
 111587,
 111590,
 111592,
 111599,
 111643,
 111694,
 111707,
 111746,
 111801,
 111876,
 111881,
 111979,
 111996,
 112097,
 112135,
 112169,
 112189,
 112200,
 112206,
 112207,
 112212,
 112213,
 112218,
 112232,
 112248,
 112263,
 112266,
 112292,
 112295,
 112298,
 112302,
 112313,
 112318,
 112321,
 112323,
 112381,
 112407,
 112428,
 112448,
 112456,
 112468,
 112566,
 112707,
 112718,
 112725,
 112726,
 112729,
 112734,
 112742,
 112744,
 112751,
 112771,
 112777,
 112785,
 112802,
 112807,
 112813,
 112819,
 112820,
 112822,
 112838,
 112849,
 112910,
 112913,
 112916,
 112925,
 112929,
 112934,
 112950,
 113007,
 113017,
 113019,
 113020,
 113030,
 113053,
 113072,
 113086,
 113093,
 113119,
 113141,
 113143,
 113170,
 113205,
 113208,
 113223,
 113244,
 113263,
 113316,
 113317,
 113338,
 113346,
 113351,
 113352,
 113353,
 113355,
 113356,
 113358,
 113366,
 113367,
 113421,
 113486,
 113494,
 113495,
 113502,
 113504,
 113515,
 113539,
 113619,
 113630,
 113675,
 113689,
 113767,
 113774,
 113799,
 113802,
 113807,
 113877,
 113878,
 113902,
 113907,
 113917,
 113921,
 113928,
 113929,
 113930,
 113936,
 113938,
 113939,
 114005,
 114042,
 114043,
 114054,
 114081,
 114089,
 114120,
 114126,
 114132,
 114220,
 114228,
 114245,
 114248,
 114255,
 114264,
 114273,
 114295,
 114297,
 114303,
 114313,
 114318,
 114339,
 114369,
 114412,
 114475,
 114476,
 114487,
 114491,
 114515,
 114517,
 114529,
 114539,
 114555,
 114575,
 114618,
 114629,
 114650,
 114756,
 114772]

In [159]:
line=[]
for i in train.index:
    if i in service.index:
        line.append(i)
    else:
        line.append(0)

service_train =train[train.index == line]

service_train['bt'] = 1

C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # Remove the CWD from sys.path while we load stuff.

In [160]:
service_train['bt']

global_id
111016    1
111037    1
111039    1
111041    1
111055    1
111061    1
111097    1
111098    1
111117    1
111140    1
111148    1
111163    1
111176    1
111180    1
111181    1
111186    1
111208    1
111246    1
111263    1
111278    1
111281    1
111313    1
111403    1
111436    1
111483    1
111573    1
111583    1
111586    1
111587    1
111590    1
         ..
114220    1
114228    1
114245    1
114248    1
114255    1
114264    1
114273    1
114295    1
114297    1
114303    1
114313    1
114318    1
114339    1
114369    1
114412    1
114475    1
114476    1
114487    1
114491    1
114515    1
114517    1
114529    1
114539    1
114555    1
114575    1
114618    1
114629    1
114650    1
114756    1
114772    1
Name: bt, Length: 195, dtype: int64

In [161]:
line2=[]
for i in train.index:
    if i in normal.index:
        line2.append(i)
    else:
        line2.append(0)
        
normal_train =train[train.index == line2]

normal_train['bt'] = 2

C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # Remove the CWD from sys.path while we load stuff.

In [162]:
line3=[]
for i in train.index:
    if i in product.index:
        line3.append(i)
    else:
        line3.append(0)
        
product_train =train[train.index == line3]

product_train['bt'] = 3

C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # Remove the CWD from sys.path while we load stuff.

In [163]:
product_train['bt']

global_id
111018    3
111021    3
111022    3
111023    3
111024    3
111045    3
111054    3
111059    3
111062    3
111064    3
111071    3
111084    3
111085    3
111089    3
111093    3
111105    3
111114    3
111121    3
111122    3
111131    3
111133    3
111136    3
111150    3
111157    3
111159    3
111172    3
111174    3
111179    3
111187    3
111189    3
         ..
114642    3
114649    3
114651    3
114654    3
114655    3
114657    3
114658    3
114659    3
114660    3
114661    3
114664    3
114671    3
114673    3
114676    3
114677    3
114678    3
114680    3
114681    3
114682    3
114689    3
114692    3
114707    3
114718    3
114728    3
114733    3
114774    3
114778    3
114779    3
114780    3
114795    3
Name: bt, Length: 834, dtype: int64

In [164]:
train = pd.concat([service_train, normal_train, product_train])

In [165]:
train

,x1,x3,x2,SEX,AGE,YEAR,MAININCM,05-Sep,04-Sep,01-Sep,...,I4S6,I4Q6,I4S7,I4Q7,I5,I6_1,I6_2,I7_1,I7_2,bt
global_id,,,,,,,,,,,,,,,,,,,,,
111016,11,73,1,1,1965.0,1989,100.0,3,1,0,...,0,3,0,3,3,6.0,8.0,1.0,3.0,1
111037,11,73,3,1,1965.0,2009,100.0,2,0,0,...,0,3,0,3,3,9.0,8.0,1.0,3.0,1
111039,11,73,1,2,1975.0,2013,100.0,2,1,0,...,0,3,0,3,1,8.0,NaN,3.0,NaN,1
111041,23,72,2,2,1964.0,2014,80.0,2,1,0,...,0,2,0,2,2,1.0,3.0,2.0,1.0,1
111055,11,62,2,1,1963.0,1999,100.0,3,0,0,...,0,2,0,2,2,3.0,7.0,2.0,NaN,1
111061,31,62,5,1,1971.0,2001,70.0,3,0,1,...,0,2,0,2,4,9.0,7.0,2.0,NaN,1
111097,11,63,3,1,1950.0,1997,100.0,3,0,1,...,0,2,0,2,1,2.0,3.0,1.0,NaN,1
111098,11,63,3,1,1957.0,2000,100.0,3,1,0,...,0,2,0,2,1,1.0,3.0,1.0,NaN,1
111117,11,58,7,1,1970.0,1998,100.0,3,1,0,...,0,3,0,3,1,9.0,8.0,1.0,3.0,1
111140,31,73,1,1,1974.0,2004,80.0,2,1,0,...,0,3,0,3,1,2.0,6.0,2.0,3.0,1
111148,11,63,4,1,1964.0,1998,100.0,3,0,1,...,0,2,0,2,1,2.0,3.0,3.0,NaN,1
111163,11,63,2,1,1967.0,2011,100.0,3,1,0,...,0,2,0,2,1,1.0,NaN,3.0,1.0,1
111176,11,63,1,2,1985.0,1999,80.0,3,1,0,...,0,3,0,3,1,9.0,NaN,1.0,NaN,1
111180,31,63,3,1,1969.0,2002,100.0,3,1,0,...,0,2,0,2,1,1.0,3.0,3.0,NaN,1
111181,11,58,6,1,1966.0,2003,100.0,3,0,1,...,0,2,0,2,1,3.0,4.0,5.0,6.0,1
111186,23,58,5,1,1968.0,2005,90.0,2,1,0,...,0,3,0,2,2,3.0,6.0,1.0,5.0,1
111208,11,63,5,1,1976.0,1999,100.0,3,1,0,...,0,1,0,1,1,3.0,NaN,1.0,3.0,1
111246,23,58,3,1,1964.0,2013,80.0,2,1,0,...,0,3,0,3,4,3.0,9.0,1.0,4.0,1
111263,23,62,7,1,1955.0,1993,100.0,3,0,0,...,0,3,0,2,1,4.0,6.0,2.0,5.0,1
111278,23,58,2,1,1958.0,2011,80.0,2,0,1,...,0,2,0,2,3,6.0,8.0,2.0,5.0,1
111281,23,63,6,1,1979.0,2012,100.0,2,1,0,...,0,2,0,1,1,3.0,5.0,1.0,3.0,1
111313,31,62,5,1,1972.0,2004,100.0,2,1,0,...,0,3,0,3,3,3.0,6.0,1.0,7.0,1
111403,34,58,2,2,1974.0,2009,100.0,3,1,0,...,0,1,0,1,1,3.0,NaN,1.0,3.0,1
111436,31,72,3,1,1957.0,2007,80.0,2,1,0,...,0,3,0,3,4,3.0,2.0,2.0,1.0,1
111483,31,73,3,1,1970.0,2009,100.0,2,1,0,...,0,3,0,3,1,3.0,NaN,3.0,NaN,1
111573,31,73,3,1,1968.0,2003,100.0,2,1,0,...,0,3,0,3,2,1.0,NaN,1.0,NaN,1
111583,31,63,5,1,1947.0,2006,100.0,3,1,0,...,0,2,0,2,1,3.0,NaN,1.0,3.0,1
111586,31,62,2,1,1975.0,2007,100.0,3,1,0,...,0,2,0,3,1,3.0,8.0,3.0,5.0,1
111587,31,73,2,1,1962.0,2007,80.0,2,1,0,...,0,3,0,3,2,4.0,8.0,1.0,2.0,1
111590,31,73,2,1,1957.0,2008,80.0,2,1,0,...,0,3,0,3,1,4.0,8.0,1.0,2.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
114642,37,26,4,1,1967.0,2005,30.0,3,0,1,...,0,3,0,3,1,1.0,2.0,1.0,5.0,3
114649,26,17,2,1,1966.0,2008,100.0,3,1,0,...,0,1,0,1,1,3.0,4.0,1.0,4.0,3
114651,37,27,2,1,1960.0,2009,70.0,2,0,1,...,0,2,0,2,1,2.0,NaN,7.0,4.0,3
114654,38,17,3,1,1959.0,2011,100.0,2,1,0,...,0,3,0,3,2,7.0,8.0,1.0,2.0,3
114655,21,26,2,1,1968.0,2012,20.0,2,1,0,...,0,4,0,3,1,3.0,NaN,1.0,5.0,3
114657,21,33,1,1,1976.0,2012,100.0,1,1,0,...,1,1,0,1,1,1.0,3.0,1.0,2.0,3
114658,38,21,2,2,1962.0,2013,100.0,1,0,1,...,0,3,0,3,2,3.0,9.0,3.0,4.0,3
114659,21,33,1,1,1971.0,2013,100.0,1,1,0,...,0,3,0,3,2,3.0,6.0,2.0,4.0,3
114660,21,23,6,1,1963.0,2014,100.0,1,0,0,...,0,1,0,1,1,1.0,NaN,4.0,NaN,3
114661,21,23,2,1,1951.0,2015,100.0,1,1,0,...,0,3,0,3,2,1.0,8.0,2.0,5.0,3
114664,38,16,1,1,1958.0,2002,90.0,3,0,0,...,0,3,0,3,2,3.0,8.0,1.0,5.0,3
114671,38,24,7,1,1957.0,1991,100.0,3,0,1,...,1,3,0,3,2,7.0,8.0,1.0,2.0,3
114673,21,29,7,1,1958.0,1991,100.0,3,0,1,...,1,1,0,1,4,1.0,3.0,1.0,7.0,3
114676,38,312,6,1,1947.0,1988,100.0,3,0,1,...,0,3,0,3,4,3.0,8.0,2.0,6.0,3
114677,38,28,6,1,1961.0,1983,100.0,3,0,1,...,0,2,0,2,2,4.0,8.0,1.0,2.0,3
114678,38,33,2,1,1962.0,1970,100.0,4,0,0,...,0,2,1,2,1,8.0,9.0,2.0,7.0,3
114680,38,25,7,1,1959.0,1996,100.0,4,0,1,...,0,2,0,2,2,1.0,8.0,2.0,4.0,3
114681,38,21,5,1,1962.0,1996,40.0,3,0,1,...,0,3,0,3,2,3.0,8.0,2.0,3.0,3
114682,38,17,7,1,1957.0,1996,100.0,3,0,1,...,0,3,0,3,2,6.0,9.0,1.0,2.0,3
114689,38,22,7,1,1960.0,1999,100.0,3,0,1,...,0,2,0,2,2,1.0,8.0,2.0,3.0,3
114692,21,17,6,1,1965.0,1999,90.0,4,0,1,...,1,1,0,1,1,8.0,3.0,1.0,3.0,3
114707,21,14,1,2,1964.0,2015,45.0,1,0,0,...,0,1,0,1,1,2.0,7.0,1.0,4.0,3
114718,21,14,3,1,1949.0,2016,100.0,1,1,0,...,0,3,0,3,2,3.0,8.0,2.0,5.0,3
114728,31,17,2,1,1957.0,2016,100.0,1,1,0,...,0,3,0,3,1,2.0,4.0,2.0,NaN,3
114733,35,34,2,1,1973.0,2016,80.0,2,1,0,...,0,3,0,3,2,9.0,6.0,3.0,5.0,3
114774,21,311,2,1,1972.0,2016,100.0,1,0,1,...,0,3,0,3,1,1.0,NaN,1.0,NaN,3
114778,26,28,1,1,1974.0,2014,100.0,2,0,0,...,0,4,0,2,1,3.0,NaN,6.0,5.0,3
114779,39,33,1,2,1973.0,2016,100.0,1,0,0,...,0,3,0,3,2,1.0,7.0,2.0,3.0,3
114780,33,21,4,1,1960.0,2015,60.0,1,1,0,...,0,1,0,1,1,1.0,3.0,1.0,4.0,3
114795,33,33,3,1,1962.0,2017,30.0,2,1,0,...,0,4,0,4,1,3.0,NaN,1.0,7.0,3

#